name: SampleWebApp CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
      uses: azure/docker-login@v1
      with:
        login-server: 'acr34223.azurecr.io'
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build ./ -t acr34223.azurecr.io/helloworld:${{ github.run_id }}
       docker push acr34223.azurecr.io/helloworld:${{ github.run_id }} 
       
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
