name: SampleWebApp CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
      uses: azure/docker-login@v1
      with:
        login-server: 'acr34223.azurecr.io'
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build ./ -t acr34223.azurecr.io/helloworld:${{ github.run_id }}
       docker push acr34223.azurecr.io/helloworld:${{ github.run_id }} 
       
    - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      uses: azure/login@v1
      with:
            client-id: ${{ '12c7bde7-b398-474e-9196-d24e044e9b26' }}
            tenant-id: ${{ '9604c138-e5d6-4c98-a4fc-2d67d6fd954e' }}
            subscription-id: ${{ '4b88b802-abfd-413d-9c62-a3357ce9b003' }} 
            enable-AzPSSession: true
